# Network architecture search scenario
scenario:
  strategy:
    name: NASEA
    framework: TensorFlow
    batch_size: 8 # required, warm-up batch size, must be greater than 0
    epochs: 20 # required, warm-up epochs, must be greater than 0
    supernet:
      input_shape: (513, 513, 3) # optional, supports format is CHW or HWC
      data_format: "channels_last" # optional, supports "channels_first" or "channels_last"
      filters: [64, 64, 128, 128, 256, 256, 512, 512] # optional, supports format is [cout,...,cout]
      strides: [1, 1, 2, 1, 2, 1, 1, 1] # optional
    constraint:
      application_type: "semantic_segmentation" # required, supports "image_classification" or "object_detection" or "semantic_segmentation"
      constraint_type: "flops" # required, supports "size" or "flops"
      constraint_value: 35000000000 # required, relate to the configuration of "constraint_type", and must be greater than 0.
    dataset:
      pre_train_dir: "/tmp/tfrecords" # required, training dataset path to pre_train or path to your checkpoint
      train_dir: "/tmp/voc_tfrecord" # required, path to your training dataset
      val_dir: "/tmp/voc_tfrecord" # required, path to your validation dataset
    searcher:
      generation_num: 100 # optional, generation number of evolutionary algorithm, must be greater than 0, default value is 100
  resource:
    name:  tensorflow_standalone # required, resource name, only support 'tensorflow_standalone'
    gpu_id: "0,1,2,3,4,5,6,7" # required, configure the gpu id list you want to use
